### ISSUE TITLE
Some errors when using the floating point data type

### ISSUE THREAD

**Issue by hanguannan** [dingqiangliu/vertica-plsql#3]
There are some errors when using data types like float, decimal, and numeric in vertica-plsql.

**Comment by dingqiangliu** [comment]
@hanguannan The issue is caused by that [FLOAT/DOUBLE/NUMERIC types are not supported in add/sub/mult/div operators](https://github.com/apache/hive/blob/0213afb8a31af1f48d009edd41cec9e6c8942354/hplsql/src/main/java/org/apache/hive/hplsql/Expression.java#L332) at now.

Now they are implemented with commit 611ea0b63667df677d2b55b753eb584b72ad6226 .
